apiVersion: aws.kubedb.com/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      key: crossplane-creds
      name: aws-credential
      namespace: crossplane-system

---

apiVersion: v1
kind: Secret
metadata:
  name: aws-credential
  namespace: crossplane-system
type: Opaque
stringData:
  crossplane-creds: |
    {
      "access_key": "?",
      "secret_key": "?"
    }

