apiVersion: rds.aws.kubedb.com/v1alpha1
kind: Proxy
metadata:
  name: example
  annotations:
    upjet.kubedb.com/manual-intervention: "This resource has a secret reference."
spec:
  forProvider:
    region: us-east-2
    auth:
      - authScheme: SECRETS
        description: example
        iamAuth: DISABLED
        secretArnRef:
          name: example
    debugLogging: false
    engineFamily: POSTGRESQL
    idleClientTimeout: 1800
    requireTls: true
    roleArnRef:
      name: role
    tags:
      Key: value
      Name: example
    vpcSubnetIds:
      - subnet-0546de20b40a2c0c1
      - subnet-030de9d358df790ad
      - subnet-09c2fc96a4cd866a7
---